services:
  frontend:
    build:
      context: .                                 # <-- repo kökü
      dockerfile: packages/frontend/Dockerfile   # <-- dosyanın gerçek yolu
    image: 585780419860.dkr.ecr.eu-west-2.amazonaws.com/justdesk-frontend:${IMAGE_TAG:-latest}   # ECR'e pushlamak için
    ports:
      - "3003:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3002
      - NEXT_PUBLIC_WS_URL=ws://backend:3002      # localhost yerine servis adı (lokalde compose içi iletişim)
    depends_on:
      - backend
    networks:
      - justdesk

  backend:
    build:
      context: .                                 # <-- repo kökü
      dockerfile: packages/backend/Dockerfile
    image: 585780419860.dkr.ecr.eu-west-2.amazonaws.com/justdesk-backend:${IMAGE_TAG:-latest}
    ports:
      - "3002:3001"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PASSWORD=defaultpassword
      - FRONTEND_URL=http://frontend:3000
    depends_on:
      - redis
    networks:
      - justdesk

  redis:
    image: redis:7-alpine       # Bunu ECR'ye push etmene gerek yok
    command: redis-server --requirepass defaultpassword
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - justdesk

networks:
  justdesk:
    driver: bridge

volumes:
  redis_data:

