version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    image: 585780419860.dkr.ecr.eu-west-2.amazonaws.com/justdesk-frontend:${IMAGE_TAG:-latest}
    ports:
      - "3003:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://yk088ow00440s884sscc4woo.18.132.204.101.sslip.io
      - NEXT_PUBLIC_WS_URL=wss://yk088ow00440s884sscc4woo.18.132.204.101.sslip.io
    depends_on:
      - backend
    networks:
      - justdesk
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    image: 585780419860.dkr.ecr.eu-west-2.amazonaws.com/justdesk-backend:${IMAGE_TAG:-latest}
    ports:
      - "3002:3001"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PASSWORD=defaultpassword
      # Frontend origin MUTLAKA dış erişilebilir domain olmalı:
      - FRONTEND_URL=https://swo4s40woc0so8wgcokok80g.18.132.204.101.sslip.io
      # Prod'da güçlü, benzersiz değerler ver:
      - SESSION_SECRET=please-change-me
      - JWT_SECRET=please-change-me-too
      - REDIS_URL=redis://:defaultpassword@redis:6379
    depends_on:
      - redis
    networks:
      - justdesk
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass defaultpassword
    # Güvenlik için internetten açma; ports kaldırıldı.
    volumes:
      - redis_data:/data
    networks:
      - justdesk
    restart: unless-stopped

networks:
  justdesk:
    driver: bridge

volumes:
  redis_data: