services:
  # Backend Service
  - type: web
    name: justdesk-backend
    env: node
    buildCommand: cd packages/backend && npm install
    startCommand: cd packages/backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: REDIS_URL
        fromService:
          type: redis
          name: justdesk-redis
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: FRONTEND_URL
        fromService:
          type: web
          name: justdesk-frontend
          property: host

  # Frontend Service
  - type: web
    name: justdesk-frontend
    env: node
    buildCommand: cd packages/frontend && npm install && npm run build
    startCommand: cd packages/frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: justdesk-backend
          property: host
      - key: NEXT_PUBLIC_WS_URL
        fromService:
          type: web
          name: justdesk-backend
          property: host

  # Redis Database
  - type: redis
    name: justdesk-redis
    ipAllowList: []
