name: Deploy Monolithic Task (2 containers)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  AWS_REGION: eu-west-2
  ECS_CLUSTER: myapp-cluster
  ECS_SERVICE: justdesk-service          # tek servis
  TASK_FAMILY: justdesk-task             # tek task family (mevcut tanım)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set env
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

      # Backend build + tag (image ID üzerinden) + push
      - name: Build backend
        run: docker compose -f docker-compose.yml build backend

      - name: Tag backend (from image ID)
        run: |
          IMG_ID=$(docker compose -f docker-compose.yml images -q backend)
          docker tag "$IMG_ID" "$ECR_REGISTRY/justdesk-backend:${IMAGE_TAG}"

      - name: Push backend
        run: docker push "$ECR_REGISTRY/justdesk-backend:${IMAGE_TAG}"

      # Frontend build + tag (image ID üzerinden) + push
      - name: Build frontend
        run: docker compose -f docker-compose.yml build frontend

      - name: Tag frontend (from image ID)
        run: |
          IMG_ID=$(docker compose -f docker-compose.yml images -q frontend)
          docker tag "$IMG_ID" "$ECR_REGISTRY/justdesk-frontend:${IMAGE_TAG}"

      - name: Push frontend
        run: docker push "$ECR_REGISTRY/justdesk-frontend:${IMAGE_TAG}"

      # Mevcut task definition'ı indir
      - name: Download task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ env.TASK_FAMILY }} \
            --query taskDefinition > task-definition.json

      # 1) Backend container image'ını render et
      - id: render_backend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: justdesk-backend-container
          image: ${{ env.ECR_REGISTRY }}/justdesk-backend:${{ env.IMAGE_TAG }}

      # 2) Frontend container image'ını (bir önceki çıktıyı baz alarak) render et
      - id: render_frontend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.render_backend.outputs.task-definition }}
          container-name: justdesk-frontend-container
          image: ${{ env.ECR_REGISTRY }}/justdesk-frontend:${{ env.IMAGE_TAG }}

      # Deploy tek servise
      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render_frontend.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
