name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}          # eu-west-2
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}        # myapp-cluster
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}        # myapp-service
  ECS_TASK_DEFINITION: ${{ secrets.ECS_TASK_DEFINITION }}  # .aws/task-definition.json
  CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}  # task def içindeki container adı (örn: myapp-container)

permissions:
  contents: read

jobs:
  deploy:
    name: Build, Push (Compose) & Deploy (ECS)
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Compose ile build/push yapacağız. Image tag olarak commit SHA kullanalım.
      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      # docker-compose.yml içinde ilgili servisin image satırı ECR'yi göstermeli:
      # image: 585780419860.dkr.ecr.eu-west-2.amazonaws.com/myapp:${IMAGE_TAG}
      - name: Build images via Docker Compose
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          docker compose -f docker-compose.yml build

      - name: Push images via Docker Compose
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          docker compose -f docker-compose.yml push

      # ECS task definition'a yeni image'i yaz
      # Tek konteyner için container-name ve image URI tek değer.
      - name: Compose export image URI (single service)
        id: image_uri
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }} # örn: myapp
        run: |
          echo "uri=${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}" >> $GITHUB_OUTPUT
      - name: Download task definition
        run: |
              aws ecs describe-task-definition --task-definition justdesk-task \
              --query taskDefinition > task-definition.json
      
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
            task-definition: task-definition.json
            container-name: ${{ secrets.MY_CONTAINER_NAME   }}
            image: ${{ steps.build-image.outputs.image }} 
            
      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ secrets.ECS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          wait-for-service-stability: true
