name: Update Changelog

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  changelog:
    if: "!contains(github.event.head_commit.message, 'skip changelog')"
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.CHANGELOG_APP_ID }}
          private_key: ${{ secrets.CHANGELOG_APP_PRIVATE_KEY }}
          installation_id: ${{ secrets.CHANGELOG_INSTALLATION_ID }}
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.ref_name }}
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Generate changelog
        run: npm run changelog
      - name: Commit changelog
        run: |
          git config user.name "justdesk-app[bot]"
          git config user.email "justdesk-app[bot]@users.noreply.github.com"
          git add docs/CHANGELOG.md
          git commit -m "chore: update changelog [skip changelog]" || echo "No changes to commit"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "chore: update changelog [skip changelog]"
          committer: "justdesk-app[bot] <justdesk-app[bot]@users.noreply.github.com>"
          author: "justdesk-app[bot] <justdesk-app[bot]@users.noreply.github.com>"
          title: "chore: update changelog"
          body: "Automated update of CHANGELOG.md"
          branch: changelog-update-${{ github.run_id }}
          base: ${{ github.ref_name }}
