name: Update Changelog

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  changelog:
    if: "!contains(github.event.head_commit.message, 'skip changelog')"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Generate changelog
        run: npm run changelog
      - name: Commit changelog
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add docs/CHANGELOG.md
          git commit -m "chore: update changelog [skip changelog]" || echo "No changes to commit"
      - name: Push changes
        run: git push
